### ISSUE TITLE
Start Tracking Package request causes error due to empty response body

### ISSUE THREAD

**Issue by jkenneydaniel** [bluefyn-international/ShipEngine#8]
Per the ShipEngine docs, the route to start tracking a package returns an empty response.

This is accessible via `startTrackingPackage` method on the Tracking trait.

Setup:
- The request is provided accurate/necessary information.

Expected result:
- Receive confirmation that request was successful signified by the expected 204 response code

Actual result:
- An exception occurs because `sendRequest` in `ShipEngineClient.php` expects the response body to be a JSON array, which it isn't (it's empty).

Their docs make mention of the expected response:
https://www.shipengine.com/docs/reference/start-tracking/

```
If successful, ShipEngine will respond with an HTTP Status Code of 204 (No Content)
```

**Comment by qschmick** [comment]
Thanks @jkenneydaniel for the detailed report. Taking a look

**Comment by qschmick** [comment]
@jkenneydaniel New release https://github.com/bluefyn-international/ShipEngine/releases/tag/v0.7.3
